### ISSUE TITLE
Compatible with many tabs

### ISSUE THREAD

**Issue by xmha97** [astroryan12/VerticalTabs#3]
Hi @astroryan12
VerticalTabs is very nice.
But it's not good when I have many tabs.
![image](https://user-images.githubusercontent.com/23485114/101228300-539eeb80-36b0-11eb-813c-64d5cc88b0f6.png)
How I can disable the tab scrollbar?

**Comment by xmha97** [comment]
I figured out how I could do that :)
Add below code to TST style rules:
```
#tabbar { scrollbar-width: none; }
```

**Comment by astroryan12** [comment]
Thanks for bringing this up and solving it! The code has been added with a slight adjustment so the scrollbar is only present when hovered over the tabs!

**Comment by xmha97** [comment]
Thanks <3
