### ISSUE TITLE
Hide VerticalTabs in full-screen mode (F11)

### ISSUE THREAD

**Issue by xmha97** [astroryan12/VerticalTabs#4]
Hi,
Please add the below feature:
- Hide VerticalTabs in full-screen mode (F11)

**Comment by astroryan12** [comment]
This has been fixed in the most recent v0.2 update which has just released! I made it so both the hover and static overlays automatically hide in fullscreen until hovered over, but the overlay layout will remain toggleable using a hotkey since that'll give you more of a choice.

**Comment by xmha97** [comment]
OK, Thanks.
