### ISSUE TITLE
Allow hiding scrollbar on hover mode until hovered

### ISSUE THREAD

**Issue by citydelver** [astroryan12/VerticalTabs#6]
Hello. I'd like to ask for a way to hide the scrollbar when the sidebar is collapsed, making it appear only when hovered. Can it be done?

![screenshot sidebar tree style tabs](https://user-images.githubusercontent.com/1512515/101246472-57536200-36f2-11eb-80cf-058e78dec58c.png)

I'm on Windows if that's relevant.

**Comment by astroryan12** [comment]
Thank you for the suggestion. This feature has been implemented in the v0.1 release!

**Comment by citydelver** [comment]
Oh, ok. But my suggestion then is to make this understandable. I couldn't find a way to do it anywhere. What should one change to achieve this (as it doesn't seem to be the default behavior)?
