### ISSUE TITLE
How to remove the "new tab" button at the bottom

### ISSUE THREAD

**Issue by citydelver** [astroryan12/VerticalTabs#7]
Hello. Could you help me removing the new tab button (and its reserved space) and using the sidebar estate exclusively for tabs?

I don't mind always using the keyboard for opening a new tab.

**Comment by astroryan12** [comment]
Thanks for the suggestion! I added this in the most recent release, just navigate to the extras folder and import the config-NoNewTab.json file into the Tree Style Tab instead of the standard config file! Enjoy!
