### ISSUE TITLE
How to change tabs "density" (make them more compact, without so much space between them)?

### ISSUE THREAD

**Issue by citydelver** [astroryan12/VerticalTabs#8]
Hello. How can I change the sidebar density, i.e., reduce the spacing between tabs and maybe also the padding between tabs and the sidebar borders?

The goal is not to get larger tabs (the same number of visible tabs, covering more area), but rather to see more tabs at once. I can only (fully) see 12 tabs at once, and I'd love to see more of them, in a more compact way.

![screenshot sidebar tree style tabs 2](https://user-images.githubusercontent.com/1512515/101262662-22a9cf80-371f-11eb-81ae-9175c4cb3fe4.png)

**Comment by astroryan12** [comment]
Hey there thanks for bringing this to my attention! You'll hopefully love the v0.1 update as it nearly doubles(!!) the amount of tabs that can be seen on screen without scrolling. Let me know what you think of the new tab density!
